// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package googlephonelib.actions;

import com.google.i18n.phonenumbers.PhoneNumberUtil;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

/**
 * Returns EXACT_MATCH if the country_code, NSN, presence of a leading zero for Italian numbers and any extension present are the same. Returns NSN_MATCH if either or both has no region specified, and the NSNs and extensions are the same. Returns SHORT_NSN_MATCH if either or both has no region specified, or the region specified is the same, and one NSN could be a shorter version of the other number. This includes the case where one has an extension specified, and the other does not. Returns NO_MATCH otherwise. For example, the numbers +1 345 657 1234 and 657 1234 are a SHORT_NSN_MATCH. The numbers +1 345 657 1234 and 345 657 are a NO_MATCH.
 */
public class isNumberMatch extends CustomJavaAction<java.lang.String>
{
	private java.lang.String firstNumberIn;
	private java.lang.String secondNumberIn;

	public isNumberMatch(IContext context, java.lang.String firstNumberIn, java.lang.String secondNumberIn)
	{
		super(context);
		this.firstNumberIn = firstNumberIn;
		this.secondNumberIn = secondNumberIn;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		PhoneNumberUtil phoneUtil = PhoneNumberUtil.getInstance();
		return phoneUtil.isNumberMatch((CharSequence)firstNumberIn, (CharSequence)secondNumberIn).toString();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "isNumberMatch";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
