// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package googlephonelib.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	// These are the constants for the GooglePhoneLib module

	public static java.lang.String getPhonenumberLogNode()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("GooglePhoneLib.PhonenumberLogNode");
	}
}