// This file was generated by Mendix Modeler 6.10.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package phonenumbercommons.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	// These are the constants for the PhoneNumberCommons module

	public static java.lang.String getPhonenumberLogNode()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("PhoneNumberCommons.PhonenumberLogNode");
	}
}