// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package googlephonelibtest.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the microflows for the GooglePhoneLibTest module
	public static void aCT_IsNumberMatch(IContext context, googlephonelibtest.proxies.TestObject _testObject)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("TestObject", _testObject == null ? null : _testObject.getMendixObject());
			Core.execute(context, "GooglePhoneLibTest.ACT_IsNumberMatch", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void aCT_ParseNumber(IContext context, googlephonelibtest.proxies.TestObject _testObject)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("TestObject", _testObject == null ? null : _testObject.getMendixObject());
			Core.execute(context, "GooglePhoneLibTest.ACT_ParseNumber", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void aCT_PossibleNumber(IContext context, googlephonelibtest.proxies.TestObject _testObject)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("TestObject", _testObject == null ? null : _testObject.getMendixObject());
			Core.execute(context, "GooglePhoneLibTest.ACT_PossibleNumber", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void aCT_ValidateNumber(IContext context, googlephonelibtest.proxies.TestObject _testObject)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("TestObject", _testObject == null ? null : _testObject.getMendixObject());
			Core.execute(context, "GooglePhoneLibTest.ACT_ValidateNumber", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static googlephonelibtest.proxies.TestObject dS_GetTestObject(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			IMendixObject result = (IMendixObject)Core.execute(context, "GooglePhoneLibTest.DS_GetTestObject", params);
			return result == null ? null : googlephonelibtest.proxies.TestObject.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
}